tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "git"

cask "docker-edge"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
